### ISSUE TITLE
Missing dependencies to run MADDOG?

### ISSUE THREAD

**Issue by ashwinssudarshan** [KathrynCampbell/MADDOG#1]
Hi! I am trying to run MADDOG but I keep encountering this problem when I run lineage assignment. It looks like certain dependencies are not available to run this command. Any way to fix this problem? Any help is appreciated. Thanks!
<img width="1272" alt="Screenshot 2021-12-21 at 12 04 29 PM" src="https://user-images.githubusercontent.com/35722075/146883167-8cd23423-c6aa-419d-bcd5-3369fd901605.png">

**Comment by KathrynCampbell** [comment]
Are you in the conda environment when you run this? Could you show me the command series that leads to the error?

**Comment by ashwinssudarshan** [comment]
Yup. So, I followed the instruction to create the coda environment using the YAML file you provided and I ran the command:-

`sh assign_lineages.sh`

I provided the folder name and reference. This is the overall error message that I got.

<img width="762" alt="Screenshot 2021-12-21 at 3 46 36 PM" src="https://user-images.githubusercontent.com/35722075/146913295-d640cabd-2582-4b0b-9a00-6c610781139d.png">

**Comment by ashwinssudarshan** [comment]
I downloaded the repository as a Zip file from Github before this

**Comment by KathrynCampbell** [comment]
Aah ok I think I see the issue. I have updated some of the functions recently. I've added the dependencies to the description and environment files in GitHub pushes, but the Zip file is slightly older. I will update it now for you! Then you'll just need to come out of the conda environment (conda deactivate MADDOG), remove the environment (conda remove --name MADDOG --all), and reinstall the environment once you've downloaded the new version.

**Comment by KathrynCampbell** [comment]
The new release is there now! You'll need to redownload it and follow the steps again, but hopefully it should work now. Also, there is a new reference in development that includes all the global RABV clades, not just cosmopolitan. So when asked for what reference you'd like, you can type RABV_WGS to get a better assignment of your sequences! This isn't listed as an option yet as I'm still adding to it, but is probably best to use.

**Comment by ashwinssudarshan** [comment]
Thanks! That issue is resolved now. I am facing a new one. Wanted to know if this is a bug in the code?
<img width="1120" alt="Screenshot 2021-12-21 at 4 35 31 PM" src="https://user-images.githubusercontent.com/35722075/146920137-e7c00375-e5ae-4a38-a869-0860925f652e.png">

**Comment by ashwinssudarshan** [comment]
If not, I can retry this on another system if there is a dependency issue. I have run this code on an old linux platform.

**Comment by KathrynCampbell** [comment]
I'm working from a Mac, and I've had some people test it on Windows too but I don't think anyone has used linux so far so it is probably that. You can run sh windows_assign_lineages.sh and that should overcome any system dependency issues

**Comment by ashwinssudarshan** [comment]
Yeah ok. Let me check and get back. Anaconda server seems to be down and I am unable to set up the condo environment on my Mac.

**Comment by ashwinssudarshan** [comment]
So, I am running into the same error on my Mac as well. Does this have anything to do with the mafft package location?

<img width="993" alt="Screenshot 2021-12-21 at 5 59 07 PM" src="https://user-images.githubusercontent.com/35722075/146930141-3bc52e0e-6d2c-467d-91ac-1bea6d66e814.png">

**Comment by KathrynCampbell** [comment]
Is this using windows_assign_lineages.sh?

**Comment by ashwinssudarshan** [comment]
Sorry. My bad. The windows_assign_lineages works. Is the RABV_WGS still in developmental stages? I got lineage assignments with Cosmo_WGS but facing issues with RABV_WGS.
<img width="752" alt="Screenshot 2021-12-21 at 6 18 58 PM" src="https://user-images.githubusercontent.com/35722075/146932598-a5a33dd3-22e2-4571-bbf0-06a7eeee82c0.png">

**Comment by KathrynCampbell** [comment]
It is, yes. I'll work on that for the release! I'm glad the Cosmo_WGS is working for you now! If you have sequences that are outside of the Cosmopolitan clade you'll need the other reference, but I can send you one that should work in the meantime; just send me an email!
