### ISSUE TITLE
Error in test_seq_assignment$lineage_countries_seen

### ISSUE THREAD

**Issue by VeterinaryLi** [KathrynCampbell/MADDOG#2]
**When I input my fasta data, the final result always showed Error.
The detailed code is as followed:**

nadd = 1217

nthread = 0

nthreadpair = 0

nthreadtb = 0

ppenalty_ex = 0

stacksize: 8192 kb

generating a scoring matrix for nucleotide (dist=200) ... done

Gap Penalty = -1.53, +0.00, +0.00

Making a distance matrix ..

There are 4393 ambiguous characters.

 2301 / 2360

done.

Constructing a UPGMA tree (efffree=0) ... 

 2350 / 2360

done.

Progressive alignment 1/2... 

STEP   501 / 2359  f

Reallocating..done. *alloclen = 24934

STEP  1901 / 2359  f

done.

Making a distance matrix from msa.. 

 2300 / 2360

done.

Constructing a UPGMA tree (efffree=1) ... 

 2350 / 2360

done.

Progressive alignment 2/2... 

STEP  1101 / 2359  f

Reallocating..done. *alloclen = 24934

STEP  2301 / 2359  f

done.

disttbfast (nuc) Version 7.508

alg=A, model=DNA200 (2), 1.53 (4.59), -0.00 (-0.00), noshift, amax=0.0

0 thread(s)

Strategy:

 FFT-NS-2 (Fast but rough)

 Progressive method (guide trees were built 2 times.)

If unsure which option to use, try 'mafft --auto input > output'.

For more information, see 'mafft --help', 'mafft --man' and the mafft page.

The default gap scoring scheme has been changed in version 7.110 (2013 Oct).

It tends to insert more gaps into gap-rich regions than previous versions.

To disable this change, add the --leavegappyregion option.

Error in test_seq_assignment$lineage_countries_seen[i] <- clusters$country[which(clusters$lineage ==  : 

Please tell me the reason, and what can I do?

**Comment by KathrynCampbell** [comment]
Hi, could you confirm the command you are using? I'm assuming this is assignment. It also appears that you're testing 1217 sequences - is that correct? This is a very large number! I have just pushed a change to GitHub, so if you're expecting your sequences to fall within the Cosmopolitan clade, this has been updated so try rerunning! If not, or if this doesn't work, a few things to try:

- Have you tested the example assignment dataset? Is this working normally?

- Try testing a smaller subset of sequences - if all your sequences are quite closely related, the assignment will struggle with a large block of over 1000 compared to the reference sequences. Test maybe 100

- Try the designation code - this required a metadata file (although for this test it can be a blank csv) and although this will take a VERY long time to complete on such a large dataset, assignment is one of the first steps in this code. If the code starts running IQ-TREE, the assignment has worked and you will find this in your folder containing the sequences and you can stop the designation run. If not, it will produce the same error before this. This will help me identify if there's an overall bug, or something wrong with the assignment code only! 

- Alternatively, you can send me your fasta file (k.campbell.1@research.gla.ac.uk) and I can identify the issue and debug for you!

**Comment by VeterinaryLi** [comment]
Thanks for your instant answer. I have added the fasta file to the attach in the previous mail. I will retry it again and  send my fasta file to the mail ***@***.***).

..




At 2022-10-02 03:45:25, "Kathryn Campbell" ***@***.***> wrote:

Hi, could you confirm the command you are using? I'm assuming this is assignment. It also appears that you're testing 1217 sequences - is that correct? This is a very large number! I have just pushed a change to GitHub, so if you're expecting your sequences to fall within the Cosmopolitan clade, this has been updated so try rerunning! If not, or if this doesn't work, a few things to try:

Have you tested the example assignment dataset? Is this working normally?

Try testing a smaller subset of sequences - if all your sequences are quite closely related, the assignment will struggle with a large block of over 1000 compared to the reference sequences. Test maybe 100

Try the designation code - this required a metadata file (although for this test it can be a blank csv) and although this will take a VERY long time to complete on such a large dataset, assignment is one of the first steps in this code. If the code starts running IQ-TREE, the assignment has worked and you will find this in your folder containing the sequences and you can stop the designation run. If not, it will produce the same error before this. This will help me identify if there's an overall bug, or something wrong with the assignment code only!

Alternatively, you can send me your fasta file ***@***.***) and I can identify the issue and debug for you!
